/*  
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jinputjoysticktestv2;
import com.sun.jna.NativeLibrary;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.io.File;
import javax.swing.*;
import net.java.games.input.Component;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;
/**
 * @author NNR
 *
 */
public class JFrameWindow extends javax.swing.JFrame {
    
    ControllerFrame controllerFrame;
    RobotIPAddressFrame robotIPFrame;
    /**
     * Creates new form JFrameWindow
     */
    public JFrameWindow() {
        // Set look and feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }        
        initComponents();
        jPanelHatSwitch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Platform Height Control", 0, 0, null, new java.awt.Color(0, 51, 255)));
        jPanelButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration Buttons", 0, 0, null, new java.awt.Color(51, 51, 255)));
        buttonInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons Functions", 0, 0, null, new java.awt.Color(51, 51, 255)));
        controllerFrame = new ControllerFrame();
        robotIPFrame = new RobotIPAddressFrame();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPanelAxes = new javax.swing.JPanel();
        jPanel_forAxis = new javax.swing.JPanel();
        jPanelXYAxis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LeftMtrRPM = new javax.swing.JLabel();
        RightMtrRPM = new javax.swing.JLabel();
        angleDpl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        velDpl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zAxisDpl = new javax.swing.JLabel();
        ConnectRobot = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        reverseDpl = new javax.swing.JLabel();
        zAxisDplActual = new javax.swing.JTextField();
        videoWindow = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        voltageLevelLabel = new javax.swing.JLabel();
        jPanelCamera = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jPanelHatSwitch = new javax.swing.JPanel();
        jComboBox_controllers = new javax.swing.JComboBox();
        buttonInfoPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        robotIP = new javax.swing.JMenuItem();
        guiController = new javax.swing.JMenuItem();
        URLMenu = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAxes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        javax.swing.GroupLayout jPanel_forAxisLayout = new javax.swing.GroupLayout(jPanel_forAxis);
        jPanel_forAxis.setLayout(jPanel_forAxisLayout);
        jPanel_forAxisLayout.setHorizontalGroup(
            jPanel_forAxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanel_forAxisLayout.setVerticalGroup(
            jPanel_forAxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        jPanelXYAxis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelXYAxisLayout = new javax.swing.GroupLayout(jPanelXYAxis);
        jPanelXYAxis.setLayout(jPanelXYAxisLayout);
        jPanelXYAxisLayout.setHorizontalGroup(
            jPanelXYAxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanelXYAxisLayout.setVerticalGroup(
            jPanelXYAxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jLabel1.setText("Steering Wheel");

        jLabel2.setText("Acceleration");

        jLabel3.setText("Brake");

        jLabel4.setText("Left MTR:");
        jLabel4.setEnabled(false);

        jLabel5.setText("Right MTR:");
        jLabel5.setEnabled(false);

        LeftMtrRPM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LeftMtrRPM.setText("0");
        LeftMtrRPM.setToolTipText("");
        LeftMtrRPM.setEnabled(false);

        RightMtrRPM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RightMtrRPM.setText("0   ");
        RightMtrRPM.setEnabled(false);

        angleDpl.setText("0");

        jLabel6.setText("Angle:");

        jLabel7.setText("Velocity:");

        velDpl.setText("0");

        jLabel10.setText("Z-Axis:");

        zAxisDpl.setText("0");

        ConnectRobot.setText("Connect Robot");
        ConnectRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectRobotActionPerformed(evt);
            }
        });

        jLabel11.setText("Reverse:");

        reverseDpl.setText("False");

        zAxisDplActual.setEditable(false);
        zAxisDplActual.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        videoWindow.setLabel("Show Video");
        videoWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoWindowActionPerformed(evt);
            }
        });

        jLabel15.setText("Battery Status:");

        voltageLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voltageLevelLabel.setText("0 V");

        javax.swing.GroupLayout jPanelAxesLayout = new javax.swing.GroupLayout(jPanelAxes);
        jPanelAxes.setLayout(jPanelAxesLayout);
        jPanelAxesLayout.setHorizontalGroup(
            jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAxesLayout.createSequentialGroup()
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                        .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAxesLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reverseDpl)
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addComponent(zAxisDpl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zAxisDplActual, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(angleDpl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(velDpl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelAxesLayout.createSequentialGroup()
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanelXYAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(jPanel_forAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAxesLayout.createSequentialGroup()
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(videoWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RightMtrRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LeftMtrRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(4, 4, 4))
                    .addGroup(jPanelAxesLayout.createSequentialGroup()
                        .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConnectRobot)
                            .addComponent(jLabel6)
                            .addGroup(jPanelAxesLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(voltageLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAxesLayout.setVerticalGroup(
            jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAxesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelXYAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_forAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(angleDpl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(velDpl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(zAxisDpl)
                    .addComponent(zAxisDplActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(reverseDpl))
                .addGap(18, 18, 18)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConnectRobot)
                    .addComponent(videoWindow))
                .addGap(18, 18, 18)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(voltageLevelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LeftMtrRPM))
                .addGap(6, 6, 6)
                .addGroup(jPanelAxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RightMtrRPM)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36))
        );

        jPanelXYAxis.getAccessibleContext().setAccessibleName("");

        jPanelCamera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanelCamera.setPreferredSize(new java.awt.Dimension(505, 316));

        javax.swing.GroupLayout jPanelCameraLayout = new javax.swing.GroupLayout(jPanelCamera);
        jPanelCamera.setLayout(jPanelCameraLayout);
        jPanelCameraLayout.setHorizontalGroup(
            jPanelCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanelCameraLayout.setVerticalGroup(
            jPanelCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelHatSwitch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hat Switch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        javax.swing.GroupLayout jPanelHatSwitchLayout = new javax.swing.GroupLayout(jPanelHatSwitch);
        jPanelHatSwitch.setLayout(jPanelHatSwitchLayout);
        jPanelHatSwitchLayout.setHorizontalGroup(
            jPanelHatSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanelHatSwitchLayout.setVerticalGroup(
            jPanelHatSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox_controllers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_controllersActionPerformed(evt);
            }
        });

        jLabel14.setText("3- Reverse Mode");

        jLabel12.setText("1- Light");

        jLabel13.setText("2- Stop Platform");

        javax.swing.GroupLayout buttonInfoPanelLayout = new javax.swing.GroupLayout(buttonInfoPanel);
        buttonInfoPanel.setLayout(buttonInfoPanelLayout);
        buttonInfoPanelLayout.setHorizontalGroup(
            buttonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonInfoPanelLayout.setVerticalGroup(
            buttonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jMenu6.setText("Options");

        robotIP.setText("Robot IP");
        robotIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotIPActionPerformed(evt);
            }
        });
        jMenu6.add(robotIP);

        guiController.setText("Controller");
        guiController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiControllerActionPerformed(evt);
            }
        });
        jMenu6.add(guiController);

        URLMenu.setText("Add URL");
        URLMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLMenuActionPerformed(evt);
            }
        });
        jMenu6.add(URLMenu);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu7.add(About);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelHatSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAxes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCamera, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelHatSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanelButtons.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_controllersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_controllersActionPerformed
        // When another controller is selected we have to remove old stuff.
        jPanelButtons.removeAll();
        jPanelButtons.repaint();
        jPanel_forAxis.removeAll();
        jPanel_forAxis.repaint();
    }//GEN-LAST:event_jComboBox_controllersActionPerformed
 //variable defined to fetch video url
    static String abc;
    static String vlcPath;
    //Option to change the URL of camera stream
    private void URLMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLMenuActionPerformed
       JMenuBar jMenuBar1 = new JMenuBar();
       final JTextField textField = new JTextField(20);
       jMenuBar1.add(textField);
       JButton jb = new JButton("GO");
       jMenuBar1.add(jb);
       
       //New JFrame to enter the URL
       final JFrame frame = new JFrame();
       jb.addActionListener(new ActionListener()
       {
            public void actionPerformed(ActionEvent ae) 
            { 
                abc=textField.getText();
                File ourFile1;
                ourFile1 = new File("D:/shishir/GUI/BasicGUI/VLC");
                vlcPath = ourFile1.getAbsolutePath();
                JoystickTest.MediaPanel(vlcPath,abc);
                frame.setVisible(false); 
            }
      });
            
            frame.add(jMenuBar1);
            frame.pack();
            frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_URLMenuActionPerformed

    private void guiControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiControllerActionPerformed
        // TODO add your handling code here:
        //controllerFrame = new ControllerFrame();
        //controllerFrame.setBounds(150, 200, 250, 350);
        controllerFrame.setVisible(true);
    }//GEN-LAST:event_guiControllerActionPerformed

    private void robotIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_robotIPActionPerformed
        // TODO add your handling code here:
        robotIPFrame.setSize(400, 150);
        robotIPFrame.setVisible(true);
        robotIPFrame.setLocation(200, 200);
    
    }//GEN-LAST:event_robotIPActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "DRHR Nubot version 1.0", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AboutActionPerformed

    private void videoWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoWindowActionPerformed
        // TODO add your handling code here:
        EmbeddedMediaPlayerComponent mediaPlayer;
        JFrame frame = new JFrame();
        //JPanel for camera feed
        JPanel mediaPanel = new JPanel();
        //mediaPanel.setBounds(6,19,493,278);
        mediaPanel.setBounds(6,14,800,600);
        //mediaPath = mediaURL;
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(),vlcPath);
        //Creates a new Media Player
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        mediaPanel.setLayout(new BorderLayout());
        mediaPanel.add(mediaPlayer, BorderLayout.CENTER);
        //Add Camera stream panel to window
        frame.add(mediaPanel);
        frame.setVisible(true);
        frame.setBounds(30, 50, 800, 600);
        //Sets the camera stream options
        String[] options = {
            ":file-caching=0",
            ":network-caching=20",
            ":sout = #transcode{vcodec=x264,vb=800,scale=0.25,acodec=none,fps=23}:display :no-sout-rtp-sap :no-sout-standard-sap :ttl=1 :sout-keep"};
        mediaPlayer.getMediaPlayer().playMedia(JoystickTest.mediaPath,options);
        //JoystickTest.ourMediaPlayer.getMediaPlayer().stop();

    }//GEN-LAST:event_videoWindowActionPerformed

    private void ConnectRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectRobotActionPerformed
        // TODO add your handling code here:
        if(JoystickTest.Robot==null)
        {
            JoystickTest.Robot = new Thread(JoystickTest.robotConn);
            JoystickTest.Robot.start();
            //JOptionPane.showMessageDialog(null, "IP Address Set Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!JoystickTest.Robot.isAlive())
        {
            JoystickTest.robotConn.setIP();
            JoystickTest.Robot = new Thread(JoystickTest.robotConn);
            JoystickTest.Robot.start();
            //JOptionPane.showMessageDialog(null, "Connection established.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Already Connected to Robot.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ConnectRobotActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem About;
    public javax.swing.JButton ConnectRobot;
    public javax.swing.JLabel LeftMtrRPM;
    public javax.swing.JLabel RightMtrRPM;
    private javax.swing.JMenuItem URLMenu;
    public javax.swing.JLabel angleDpl;
    private javax.swing.JPanel buttonInfoPanel;
    public javax.swing.JMenuItem guiController;
    private javax.swing.JComboBox jComboBox_controllers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanelAxes;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCamera;
    private javax.swing.JPanel jPanelHatSwitch;
    private javax.swing.JPanel jPanelXYAxis;
    private javax.swing.JPanel jPanel_forAxis;
    public javax.swing.JLabel reverseDpl;
    public javax.swing.JMenuItem robotIP;
    public javax.swing.JLabel velDpl;
    private javax.swing.JButton videoWindow;
    public javax.swing.JLabel voltageLevelLabel;
    public javax.swing.JLabel zAxisDpl;
    public javax.swing.JTextField zAxisDplActual;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public int getSelectedControllerName(){
        return jComboBox_controllers.getSelectedIndex();
    }
    
    public void addControllerName(String controllerName){
        jComboBox_controllers.addItem(controllerName);
    }
    
    public void showControllerDisconnected(){
        jComboBox_controllers.removeAllItems();
        jComboBox_controllers.addItem("Controller disconnected!");
    }
     public void setXYAxis(double xPercentage, double yPercentage){
        Graphics2D g2d = (Graphics2D)jPanelXYAxis.getGraphics();
        g2d.clearRect(1, 1, jPanelXYAxis.getWidth() - 2, jPanelXYAxis.getHeight() - 2);
        
    }
    
    //Indicates the inclination of the steering wheel
    public void line (double angle)
    {     
          Graphics2D g2d = (Graphics2D)jPanelXYAxis.getGraphics();
          double a = 50*Math.cos(Math.toRadians(angle));
          int x = (int) a;
          double b = 50*Math.sin(Math.toRadians(angle));
          int y = (int) b;
          x = 55-x;
          y = 88-y;
          g2d.setColor(Color.blue);
          g2d.drawLine(55,88,x,y);   
    }
    
    public void arc ()
    {
       Graphics2D g2d = (Graphics2D)jPanelXYAxis.getGraphics();
       g2d.setColor(Color.red); 
       g2d.drawArc(5,38,100,100,0,180);
       g2d.setColor(Color.black);
       g2d.drawString("0",5,96);
       g2d.drawString("90",51,37);
       g2d.drawString("180",92,96); 
    }
    
    public void setControllerButtons(JPanel buttonsPanel){
        jPanelButtons.removeAll();
        jPanelButtons.add(buttonsPanel);
        jPanelButtons.validate();
    }
    

    public void setHatSwitch(float hatSwitchPosition) {
        int circleSize = 100;
        
        Graphics2D g2d = (Graphics2D)jPanelHatSwitch.getGraphics();
        //g2d.clearRect(5, 15, jPanelHatSwitch.getWidth() - 10, jPanelHatSwitch.getHeight() - 22);
        g2d.clearRect(5, 15, jPanelHatSwitch.getWidth() - 10, jPanelHatSwitch.getHeight() - 19);
        //g2d.drawOval(190, 20, circleSize, circleSize);
        g2d.drawOval(70, 20, circleSize, circleSize);
        
        if(Float.compare(hatSwitchPosition, Component.POV.OFF) == 0)
            return;
        
//        int smallCircleSize = 10;
//        int upCircleX = 235;
//        int upCircleY = 15;
//        int leftCircleX = 185;
//        int leftCircleY = 66;
//        int betweenX = 37;
//        int betweenY = 17;
        int smallCircleSize = 10;
        int upCircleX = 115;
        int upCircleY = 15;
        int leftCircleX = 65;
        int leftCircleY = 66;
        int betweenX = 37;
        int betweenY = 17;
        int x = 0;
        int y = 0;
        
        g2d.setColor(Color.blue);
                        
        if(Float.compare(hatSwitchPosition, Component.POV.UP) == 0){
            x = upCircleX;
            y = upCircleY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.DOWN) == 0){
            x = upCircleX;
            y = upCircleY + circleSize;
        }else if(Float.compare(hatSwitchPosition, Component.POV.LEFT) == 0){
            x = leftCircleX;
            y = leftCircleY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.RIGHT) == 0){
            x = leftCircleX + circleSize;
            y = leftCircleY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.UP_LEFT) == 0){
            x = upCircleX - betweenX;
            y = upCircleY + betweenY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.UP_RIGHT) == 0){
            x = upCircleX + betweenX;
            y = upCircleY + betweenY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.DOWN_LEFT) == 0){
            x = upCircleX - betweenX;
            y = upCircleY + circleSize - betweenY;
        }else if(Float.compare(hatSwitchPosition, Component.POV.DOWN_RIGHT) == 0){
            x = upCircleX + betweenX;
            y = upCircleY + circleSize - betweenY;
        }
        
        g2d.fillOval(x, y, smallCircleSize, smallCircleSize);
    }
     
    public void addAxisPanel(javax.swing.JPanel axesPanel){
        jPanel_forAxis.removeAll();
        jPanel_forAxis.add(axesPanel);
        jPanel_forAxis.validate();
    }
    
    public void camera(javax.swing.JPanel mediaPanel) {
        jPanelCamera.removeAll();
        jPanelCamera.add(mediaPanel);
        jPanelCamera.validate();
    }
}